const fs = require("fs");

// file paths pages
const indexNotesDir = "./src/pages/index-notes";
const literatureNotesDir = "./src/pages/literature-notes";
const fleetingNotesDir = "./src/pages/fleeting-notes";

// read the file to get an array of file in the directory
const indexNotesFileNames = fs.readdirSync(indexNotesDir);
const literatureNotesFileNames = fs.readdirSync(literatureNotesDir);
const fleetingNotesFileNames = fs.readdirSync(fleetingNotesDir);

// loop over each of the filename to build a string for netlify _redirects file
const indexNoteRedirects = indexNotesFileNames.map((fileName) => {
  const fileWithoutExtension = fileName.split(".")[0];
  return `/index-notes/${fileName}  /index-notes/${fileWithoutExtension}`;
});

const literatureNoteRedirects = literatureNotesFileNames.map((fileName) => {
  const fileWithoutExtension = fileName.split(".")[0];
  return `/literature-notes/${fileName}  /literature-notes/${fileWithoutExtension}`;
});

const fleetingNoteRedirects = fleetingNotesFileNames.map((fileName) => {
  const fileWithoutExtension = fileName.split(".")[0];
  return `/fleeting-notes/${fileName}  /fleeting-notes/${fileWithoutExtension}`;
});

const allRedirects = [
  `
# THIS FILE IS AUTOGENERATED BY updateRedirects.js.
  `,
  "# INDEX NOTES",
  ...indexNoteRedirects,
  "# LITERATURE NOTES",
  ...literatureNoteRedirects,
  "# FLEETING NOTES",
  ...fleetingNoteRedirects,
].join("\n");

fs.writeFile("./public/_redirects", allRedirects, (err) => {
  if (err) {
    return console.log(err);
  }
  console.log("Netlify _redirects file was updated");
});
