name: Redeploy chiubaca.com

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Redeploy chiubaca.com
        run: |
          curl -X POST \
            https://api.github.com/repos/chiubaca/chiubaca-monorepo/actions/workflows/deploy.yml/dispatches \
            -H "Authorization: token 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" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"ref":"main"}'
