name: Redeploy chiubaca.com

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Redeploy chiubaca.com
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/workers/builds/deploy_hooks/d39898a6-a6d6-4b74-a0dd-a320ce82e86e"
